export function genGeneratedNotice(generator: Function) {
  return `/**
 * DO NOT MODIFY OR FORMAT MANUALLY
 * THIS IS A GENERATED FILE
 *
 * This file is automatically generated with the module: ${generator.name}
 */

`;
}
