export function genGeneratedNotice(generator: Function, codeHash: string) {
  return `/**
 * DO NOT MODIFY OR FORMAT MANUALLY
 * THIS IS A GENERATED FILE
 *
 * This file is automatically generated with the module: ${generator.name}
 *
 * Generated sha256 hash in hex for code after this section is:
 * ${codeHash}
 */
`;
}
